mmpose_model: "rtmpose-x_8xb256-700e_body8-halpe26-384x288"
input_video: "path/to/the/input/video"
detection:
  output: "path/to/the/desired/output/detection/file.yml"
  threshold: 0.5
  visualize: True
  max_length: -1  # -1 means no limit
  visualize_size:
    - 1280
    - 720
tracking:
  output: "path/to/the/desired/output/tracking/and/detection/file.yml"
